#!/bin/bash
# Opera browser on Ubuntu has a big issue of not being able to play some video formats due to a licensing issue with ffmpeg.
# So this is a hack to get it linked with a 3rd party
# (installed via snap - the other version didn't work) ffmpeg repository to make the browser play videos again.
# Dependencies: sudo snap install chromium-ffmpeg

    SUBSTRING="95241/"
    biggest="104195"
    
    SUBSTRING=${SUBSTRING%/}
    

    if [[ $SUBSTRING -gt $biggest ]]
     then
        biggest=$SUBSTRING
     fi
     
echo $biggest $SUBSTRING
