#!/bin/bash
# this script will get an input of a process and will kill it
# essentially a shortcut to get something killed instantly (pun intended)

killone phpstorm
killone postman
killone opera
killone snap-store
killone steam
