#!/bin/bash

HOST='nipunadodan.com'
USER='nipunadodan'
PASSWD='FoL!W?W%Hpf6'
LOCALPATH='~/html/nsd/react/archives_edu_react/build/'
FILE=*
DIR='lab/archives/'

cd $LOCALPATH
#tar -cvf archives.tar *

#ncftp -u $USER -p $PASSWD nipunadodan.com

ncftpput -R -v -u "$USER" -p "$PASSWD" nipunadodan.com $DIR $LOCALPATH
