#!/bin/bash
# Opera browser on Ubuntu has a big issue of not being able to play some video formats due to a licensing issue with ffmpeg.
# So this is a hack to get it linked with a 3rd party
# (installed via snap - the other version didn't work) ffmpeg repository to make the browser play videos again.
# Dependencies: sudo snap install chromium-ffmpeg

for d in /snap/chromium-ffmpeg/current/chromium-ffmpeg-*/ ; do
    SUBSTRING=$(echo $d| cut -d'-' -f 4)
    SUBSTRING=${SUBSTRING%/}
    
    biggest=0
    
    if [[ $SUBSTRING -gt $biggest ]]
     then
        biggest="$SUBSTRING"
     fi

done

killall opera
cd /usr/lib/x86_64-linux-gnu/opera
sudo mv libffmpeg.so libffmpeg.so.bak
sudo ln -sf /snap/chromium-ffmpeg/current/chromium-ffmpeg-"$biggest"/chromium-ffmpeg/libffmpeg.so libffmpeg.so
echo "DONE"
