#!/bin/bash
for d in /snap/chromium-ffmpeg/current/chromium-ffmpeg-*/ ; do
    #echo "$d"
    SUBSTRING=$(echo $d| cut -d'-' -f 4)
    SUBSTRING=${SUBSTRING%/}
    #echo $SUBSTRING
    
    biggest=0
    
    if [[ $SUBSTRING -gt $biggest ]]
     then
        biggest="$SUBSTRING"
     fi
    
done

killall opera
cd /usr/lib/x86_64-linux-gnu/opera
sudo mv libffmpeg.so libffmpeg.so.bak
sudo ln -sf /snap/chromium-ffmpeg/current/chromium-ffmpeg-"$biggest"/chromium-ffmpeg/libffmpeg.so libffmpeg.so
echo "DONE"
